"""add panel reading contracts

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-08 16:32:28.015109
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node_insight_section",
        sa.Column(
            "section_id", sa.BigInteger(), sa.Identity(always=True), nullable=False
        ),
        sa.Column("node_insight_id", sa.BigInteger(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("synthesis_text", sa.Text(), nullable=False),
        sa.Column("caveat_text", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "btrim(title) <> '' AND btrim(synthesis_text) <> ''",
            name="ck_node_insight_section__text",
        ),
        sa.CheckConstraint(
            "caveat_text IS NULL OR btrim(caveat_text) <> ''",
            name="ck_node_insight_section__caveat",
        ),
        sa.CheckConstraint("display_order > 0", name="ck_node_insight_section__order"),
        sa.ForeignKeyConstraint(
            ["node_insight_id"],
            ["node_insight.node_insight_id"],
            name="fk_node_insight_section__node_insight",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("section_id", name="pk_node_insight_section"),
        sa.UniqueConstraint(
            "node_insight_id", "display_order", name="uq_node_insight_section__order"
        ),
        comment="종합보고서의 주요 발견과 해석. 사실은 기존 Claim을 참조한다.",
    )
    op.create_table(
        "node_insight_window",
        sa.Column(
            "insight_window_id",
            sa.BigInteger(),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column("node_id", sa.BigInteger(), nullable=False),
        sa.Column("node_search_document_id", sa.BigInteger(), nullable=False),
        sa.Column("model_task_id", sa.BigInteger(), nullable=False),
        sa.Column("time_window", sa.Text(), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("node_insight_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "time_window IN ('RECENT_90_DAYS', 'RECENT_1_YEAR')",
            name="ck_node_insight_window__window",
        ),
        sa.CheckConstraint("isfinite(as_of_at)", name="ck_node_insight_window__as_of"),
        sa.ForeignKeyConstraint(
            ["model_task_id"],
            ["model_task.model_task_id"],
            name="fk_node_insight_window__model_task",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.node_id"],
            name="fk_node_insight_window__node",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_insight_id"],
            ["node_insight.node_insight_id"],
            name="fk_node_insight_window__node_insight",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_search_document_id"],
            ["node_search_document.node_search_document_id"],
            name="fk_node_insight_window__node_search_document",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("insight_window_id", name="pk_node_insight_window"),
        sa.UniqueConstraint(
            "model_task_id", "time_window", name="uq_node_insight_window__task_window"
        ),
        comment="선택된 작업의 기간별 종합보고서 준비 결과. NULL 보고서는 정상 0개이며 빈 분석을 저장하지 않는다.",
    )
    op.create_table(
        "node_question_set",
        sa.Column(
            "question_set_id", sa.BigInteger(), sa.Identity(always=True), nullable=False
        ),
        sa.Column("node_context_id", sa.BigInteger(), nullable=False),
        sa.Column("model_task_id", sa.BigInteger(), nullable=False),
        sa.Column("time_window", sa.Text(), nullable=False),
        sa.Column("as_of_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "time_window IN ('RECENT_90_DAYS', 'RECENT_1_YEAR')",
            name="ck_node_question_set__window",
        ),
        sa.CheckConstraint("isfinite(as_of_at)", name="ck_node_question_set__as_of"),
        sa.ForeignKeyConstraint(
            ["model_task_id"],
            ["model_task.model_task_id"],
            name="fk_node_question_set__model_task",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_context_id"],
            ["node_context.node_context_id"],
            name="fk_node_question_set__node_context",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("question_set_id", name="pk_node_question_set"),
        sa.UniqueConstraint(
            "node_context_id",
            "time_window",
            name="uq_node_question_set__context_window",
        ),
        comment="공개 context의 기간별 불변 질문 묶음. 성공한 빈 묶음과 미준비를 구분한다.",
    )
    op.create_table(
        "node_insight_section_claim",
        sa.Column("section_id", sa.BigInteger(), nullable=False),
        sa.Column("claim_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "role IN ('KEY_CLAIM', 'SUPPORTING_CLAIM', 'CONTRASTING_CLAIM')",
            name="ck_node_insight_section_claim__role",
        ),
        sa.CheckConstraint(
            "display_order > 0", name="ck_node_insight_section_claim__order"
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.claim_id"],
            name="fk_node_insight_section_claim__claim",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["node_insight_section.section_id"],
            name="fk_node_insight_section_claim__node_insight_section",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "section_id", "claim_id", name="pk_node_insight_section_claim"
        ),
        sa.UniqueConstraint(
            "section_id", "display_order", name="uq_node_insight_section_claim__order"
        ),
        comment="생성물이 사용하는 기존 Claim과 역할·순서. 원문과 사실의 사본을 만들지 않는다.",
    )
    op.create_table(
        "node_question",
        sa.Column(
            "question_id", sa.BigInteger(), sa.Identity(always=True), nullable=False
        ),
        sa.Column("question_set_id", sa.BigInteger(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("caveat_text", sa.Text(), nullable=True),
        sa.Column("section_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "btrim(question_text) <> '' AND btrim(answer_text) <> ''",
            name="ck_node_question__text",
        ),
        sa.CheckConstraint(
            "caveat_text IS NULL OR btrim(caveat_text) <> ''",
            name="ck_node_question__caveat",
        ),
        sa.CheckConstraint("display_order > 0", name="ck_node_question__order"),
        sa.ForeignKeyConstraint(
            ["question_set_id"],
            ["node_question_set.question_set_id"],
            name="fk_node_question__node_question_set",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["node_insight_section.section_id"],
            name="fk_node_question__node_insight_section",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("question_id", name="pk_node_question"),
        sa.UniqueConstraint(
            "question_set_id", "display_order", name="uq_node_question__order"
        ),
        comment="현재 노드를 이해하는 질문과 저장 답변. 클릭으로 지도의 중심을 바꾸지 않는다.",
    )
    op.create_table(
        "node_question_claim",
        sa.Column("question_id", sa.BigInteger(), nullable=False),
        sa.Column("claim_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "role IN ('KEY_CLAIM', 'SUPPORTING_CLAIM', 'CONTRASTING_CLAIM')",
            name="ck_node_question_claim__role",
        ),
        sa.CheckConstraint("display_order > 0", name="ck_node_question_claim__order"),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.claim_id"],
            name="fk_node_question_claim__claim",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["node_question.question_id"],
            name="fk_node_question_claim__node_question",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "question_id", "claim_id", name="pk_node_question_claim"
        ),
        sa.UniqueConstraint(
            "question_id", "display_order", name="uq_node_question_claim__order"
        ),
        comment="생성물이 사용하는 기존 Claim과 역할·순서. 원문과 사실의 사본을 만들지 않는다.",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    occupied = op.get_bind().scalar(
        sa.text("""
        SELECT EXISTS (SELECT 1 FROM node_question_set)
          OR EXISTS (SELECT 1 FROM node_insight_window)
          OR EXISTS (SELECT 1 FROM node_insight_section)
    """)
    )
    if occupied:
        raise RuntimeError(
            "패널 결과가 존재합니다. 스키마를 보존한 채 앱을 되돌리세요."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("node_question_claim")
    op.drop_table("node_question")
    op.drop_table("node_insight_section_claim")
    op.drop_table("node_question_set")
    op.drop_table("node_insight_window")
    op.drop_table("node_insight_section")
    # ### end Alembic commands ###
